# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_dtm <- function(path) {
    .Call('_RCudaNlp_read_dtm', PACKAGE = 'RCudaNlp', path)
}

normalize_dtm <- function(dtm) {
    .Call('_RCudaNlp_normalize_dtm', PACKAGE = 'RCudaNlp', dtm)
}

